<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1643926466843' stop='1643926488340'>
    <name>Contact</name>
    <title>Contact</title>
    <test-cases>
        <test-case start='1643926466843' status='failed' stop='1643926488339'>
            <name>Fill all the input fields, submit form and assert success message</name>
            <title>Fill all the input fields, submit form and assert success message</title>
            <labels>
                <label name='language' value='javascript'/>
                <label name='framework' value='wdio'/>
                <label name='thread' value='1-0'/>
            </labels>
            <parameters>
                <parameter kind='argument' name='browser' value='firefox-96.0.3'/>
            </parameters>
            <steps/>
            <attachments>
                <attachment title='Screenshot' source='12be1585-74fa-409a-a9c1-27d29777252d-attachment.png' type='image/png' size='1149798'/>
            </attachments>
            <failure>
                <message>Expect $(`[role="alert"]`) to have text containing
                
                Expected: "Thank you for contacting us! We will be in touch with you shortly"
                Received: "Thanks for contacting us! We will be in touch with you shortly"</message>
                <stack-trace>Error: Expect $(`[role="alert"]`) to have text containing
                
                Expected: "Thank you for contacting us! We will be in touch with you shortly"
                Received: "Thanks for contacting us! We will be in touch with you shortly"
                    at Context.&lt;anonymous> (/Users/holleyvoegtle/Desktop/Projects for CCCareers/wdio-course/test/specs/contact.js:22:36)
                    at processTicksAndRejections (node:internal/process/task_queues:96:5)</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>